### ISSUE TITLE
Not an issue but an extra `for` loop in ui.rs

### ISSUE THREAD

**Issue by manishkumar1983** [thomas-mauran/tic-tac-toe#1]
First of all thanks for sharing this code and equipping us with knowledge on TUI. 
Wanted to start learning TUI with app like this which is simple and easy to understand control flow.

While code walkthrough found out an extra loop in ui.rs file.
I see that we don't need following loop on line 94
```for row in layout_vertical.chunks(3) {```

instead just swap the variable `row`  on line 95 with `layout_vertical` and it gives same app usability.
```for (chunk_index, chunk) in layout_vertical.iter().enumerate() {```

Idea is to find out if I am missing anything or the catch is right?

**Comment by thomas-mauran** [comment]
You are entirely right ! I'd be happy to accept a fix if you want to contribute and open a PR, else I'll do it myself.
Thank you !
